branches:
  only:
  - master
language: node_js

sudo: false

node_js:
    - 'stable'

before_install:
- git config --global user.name "tangleithu"
- git config --global user.email travis@tanglei.name
- git clone --recursive -b master git@github.com:tl3shi/hexo.tanglei.name .deploy_git

install:
- npm install hexo-cli -g
- npm install

script:
- hexo clean
- hexo g
- hexo d
