branches:
  only:
  - master
language: node_js

sudo: false

node_js:
    - 'stable'

before_install:
- git config --global user.name "tangleithu"
- git config --global user.email travis@tanglei.name

install:
- npm install hexo-cli -g
- npm install

script:
- hexo clean
- hexo g
- cd .deploy && git add -A . && git commit -m "commit from travis" 
- git push --force "https://23d3d1866b4b2c8428aa669ee3c9ea8967231eb3@github.com/tl3shi/hexo.tanglei.name" master:gh-pages 
